language: cpp

compiler:
  - clang
  - gcc
  - g++
  - clang++

dist: trusty

os:
  - linux
  - osx

sudo: true

addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
   - gcc-4.8
   - g++-4.8

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ln -sf /usr/bin/gcc-4.8 /usr/bin/gcc; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ln -sf /usr/bin/g++-4.8 /usr/bin/g++; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; tehn sudo apt-get install -y libwxbase3.0-dev libwxgtk3.0-dev; fi
  - make

script: ./bin/bss

notifications:
    email:
        - lsferreira169@gmail.com
