language: cpp

compiler:
  - clang
  - gcc
  - g++
  - clang++

os:
  - linux
  - osx

sudo: false

addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
   - gcc-4.8
   - g++-4.8

install:
  - if [ "$CC" = "gcc" ]; then export CC="gcc-4.8"; fi
  - if [ "$CPP" = "g++" ]; then export CPP="g++-4.8"; fi

before_script: make

script: ./bin/bss

notifications:
    email:
        - lsferreira169@gmail.com
