# -*- Makefile -*- 
# __________  _________ _________
# \______   \/   _____//   _____/  | BigSource Script
#  |    |  _/\_____  \ \_____  \   | Project in C/C++ Language
#  |    |   \/        \/        \  |
#  |______  /_______  /_______  /  | @author Luís Ferreira
#         \/        \/        \/   | @license GNU Public License v3
# Copyright (C) 2016 - Luís Ferreira. All right reserved
# 
# This makefile was generated by 'cbp2make' tool rev.147            
# More information in: https://github.com/ljmf00/ (Github Page)


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall -fexceptions
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = bin/obj/debug
DEP_DEBUG = 
OUT_DEBUG = bin/debug/bss

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = bin/obj/release
DEP_RELEASE = 
OUT_RELEASE = bin/release/bss

OBJ_DEBUG = $(OBJDIR_DEBUG)/lib/misc/files.o $(OBJDIR_DEBUG)/lib/main.o $(OBJDIR_DEBUG)/lib/crypto/sha3/sha3.o $(OBJDIR_DEBUG)/lib/crypto/sha2/sha2.o $(OBJDIR_DEBUG)/lib/crypto/sha1/sha1.o $(OBJDIR_DEBUG)/lib/crypto/keccak/keccak.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/lib/misc/files.o $(OBJDIR_RELEASE)/lib/main.o $(OBJDIR_RELEASE)/lib/crypto/sha3/sha3.o $(OBJDIR_RELEASE)/lib/crypto/sha2/sha2.o $(OBJDIR_RELEASE)/lib/crypto/sha1/sha1.o $(OBJDIR_RELEASE)/lib/crypto/keccak/keccak.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/debug || mkdir -p bin/debug
	test -d $(OBJDIR_DEBUG)/lib/misc || mkdir -p $(OBJDIR_DEBUG)/lib/misc
	test -d $(OBJDIR_DEBUG)/lib || mkdir -p $(OBJDIR_DEBUG)/lib
	test -d $(OBJDIR_DEBUG)/lib/crypto/sha3 || mkdir -p $(OBJDIR_DEBUG)/lib/crypto/sha3
	test -d $(OBJDIR_DEBUG)/lib/crypto/sha2 || mkdir -p $(OBJDIR_DEBUG)/lib/crypto/sha2
	test -d $(OBJDIR_DEBUG)/lib/crypto/sha1 || mkdir -p $(OBJDIR_DEBUG)/lib/crypto/sha1
	test -d $(OBJDIR_DEBUG)/lib/crypto/keccak || mkdir -p $(OBJDIR_DEBUG)/lib/crypto/keccak

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/lib/misc/files.o: lib/misc/files.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c lib/misc/files.cpp -o $(OBJDIR_DEBUG)/lib/misc/files.o

$(OBJDIR_DEBUG)/lib/main.o: lib/main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c lib/main.cpp -o $(OBJDIR_DEBUG)/lib/main.o

$(OBJDIR_DEBUG)/lib/crypto/sha3/sha3.o: lib/crypto/sha3/sha3.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c lib/crypto/sha3/sha3.cpp -o $(OBJDIR_DEBUG)/lib/crypto/sha3/sha3.o

$(OBJDIR_DEBUG)/lib/crypto/sha2/sha2.o: lib/crypto/sha2/sha2.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c lib/crypto/sha2/sha2.cpp -o $(OBJDIR_DEBUG)/lib/crypto/sha2/sha2.o

$(OBJDIR_DEBUG)/lib/crypto/sha1/sha1.o: lib/crypto/sha1/sha1.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c lib/crypto/sha1/sha1.cpp -o $(OBJDIR_DEBUG)/lib/crypto/sha1/sha1.o

$(OBJDIR_DEBUG)/lib/crypto/keccak/keccak.o: lib/crypto/keccak/keccak.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c lib/crypto/keccak/keccak.cpp -o $(OBJDIR_DEBUG)/lib/crypto/keccak/keccak.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/debug
	rm -rf $(OBJDIR_DEBUG)/lib/misc
	rm -rf $(OBJDIR_DEBUG)/lib
	rm -rf $(OBJDIR_DEBUG)/lib/crypto/sha3
	rm -rf $(OBJDIR_DEBUG)/lib/crypto/sha2
	rm -rf $(OBJDIR_DEBUG)/lib/crypto/sha1
	rm -rf $(OBJDIR_DEBUG)/lib/crypto/keccak

before_release: 
	test -d bin/release || mkdir -p bin/release
	test -d $(OBJDIR_RELEASE)/lib/misc || mkdir -p $(OBJDIR_RELEASE)/lib/misc
	test -d $(OBJDIR_RELEASE)/lib || mkdir -p $(OBJDIR_RELEASE)/lib
	test -d $(OBJDIR_RELEASE)/lib/crypto/sha3 || mkdir -p $(OBJDIR_RELEASE)/lib/crypto/sha3
	test -d $(OBJDIR_RELEASE)/lib/crypto/sha2 || mkdir -p $(OBJDIR_RELEASE)/lib/crypto/sha2
	test -d $(OBJDIR_RELEASE)/lib/crypto/sha1 || mkdir -p $(OBJDIR_RELEASE)/lib/crypto/sha1
	test -d $(OBJDIR_RELEASE)/lib/crypto/keccak || mkdir -p $(OBJDIR_RELEASE)/lib/crypto/keccak

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/lib/misc/files.o: lib/misc/files.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c lib/misc/files.cpp -o $(OBJDIR_RELEASE)/lib/misc/files.o

$(OBJDIR_RELEASE)/lib/main.o: lib/main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c lib/main.cpp -o $(OBJDIR_RELEASE)/lib/main.o

$(OBJDIR_RELEASE)/lib/crypto/sha3/sha3.o: lib/crypto/sha3/sha3.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c lib/crypto/sha3/sha3.cpp -o $(OBJDIR_RELEASE)/lib/crypto/sha3/sha3.o

$(OBJDIR_RELEASE)/lib/crypto/sha2/sha2.o: lib/crypto/sha2/sha2.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c lib/crypto/sha2/sha2.cpp -o $(OBJDIR_RELEASE)/lib/crypto/sha2/sha2.o

$(OBJDIR_RELEASE)/lib/crypto/sha1/sha1.o: lib/crypto/sha1/sha1.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c lib/crypto/sha1/sha1.cpp -o $(OBJDIR_RELEASE)/lib/crypto/sha1/sha1.o

$(OBJDIR_RELEASE)/lib/crypto/keccak/keccak.o: lib/crypto/keccak/keccak.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c lib/crypto/keccak/keccak.cpp -o $(OBJDIR_RELEASE)/lib/crypto/keccak/keccak.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/release
	rm -rf $(OBJDIR_RELEASE)/lib/misc
	rm -rf $(OBJDIR_RELEASE)/lib
	rm -rf $(OBJDIR_RELEASE)/lib/crypto/sha3
	rm -rf $(OBJDIR_RELEASE)/lib/crypto/sha2
	rm -rf $(OBJDIR_RELEASE)/lib/crypto/sha1
	rm -rf $(OBJDIR_RELEASE)/lib/crypto/keccak

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release