# -*- Makefile -*- 
# __________  _________ _________
# \______   \/   _____//   _____/  | BigSource Script
#  |    |  _/\_____  \ \_____  \   | Project in C/C++ Language
#  |    |   \/        \/        \  |
#  |______  /_______  /_______  /  | @author Luís Ferreira
#         \/        \/        \/   | @license GNU Public License v3
# Copyright (C) 2016 - Luís Ferreira. All right reserved
# 
# This makefile was generated by 'cbp2make' tool rev.147            
# More information in: https://github.com/ljmf00/ (Github Page)

NAME = bss
CC = gcc
CPP = g++
RM = rm -rf
MKDIR = mkdir -p

all: 
	$(MKDIR) bin/obj/crypto
	$(MKDIR) bin/obj/misc
	$(CPP) -c lib/main.cpp -o bin/obj/main.o
	$(CPP) -c lib/crypto/sha1/sha1.cpp -o bin/obj/crypto/sha1.o
	$(CPP) -c lib/crypto/sha2/sha2.cpp -o bin/obj/crypto/sha2.o
	$(CPP) -c lib/crypto/sha3/sha3.cpp -o bin/obj/crypto/sha3.o
	$(CPP) -o bin/bss bin/obj/main.o bin/obj/crypto/sha1.o bin/obj/crypto/sha2.o bin/obj/crypto/sha3.o

clean:
	$(RM) bin